### ISSUE TITLE
[not tea] Standards/Guidelines not wrapping in nav

### ISSUE THREAD

**Issue by slhenry** [w3c/wai-std-gl-overview#13]
![image](https://user-images.githubusercontent.com/6991814/54794653-7bb59500-4c16-11e9-88d6-60ae03f092e2.png)

I think that it used to and it quit within the last month. Maybe when you rolled out the translations?

**Comment by yatil** [comment]
Was addressed with this commit last week: https://github.com/w3c/wai-website-data/commit/07bf853d159696e7440e33838e4f826da9957194

The change just has not been deployed yet :-)
