### ISSUE TITLE
[es] update needed - Resumen de los estándares de accesibilidad de W3C 

### ISSUE THREAD

**Issue by shawna-slh** [w3c/wai-std-gl-overview#47]
Hi @cmuncharaz 

We will be promoting translations the week of 17 May, along with Global Accessibility Awareness Day (GAAD).

Would you be able to update this translation before then? Or, should we ask someone else to update it?

The updates needed are listed in the changelog at:
	https://www.w3.org/WAI/standards-guidelines/changelog/
	
Here is the file:
https://raw.githubusercontent.com/w3c/wai-std-gl-overview/master/content/index.es.md

You can submit the edits as a pull request, or sent the updated file to group-wai-translations@w3.org

**Comment by cmuncharaz** [comment]
Hi @shawna-slh! Sorry for the late reply. I can update the translations. Checking that.

**Comment by cmuncharaz** [comment]
Pull request sent:
https://github.com/w3c/wai-std-gl-overview/pull/59
