### ISSUE TITLE
[zh-hans] update needed to W3C 可访问性标准概述 

### ISSUE THREAD

**Issue by shawna-slh** [w3c/wai-std-gl-overview#49]
Hi @anjia 

We will be promoting translations the week of 17 May, along with Global Accessibility Awareness Day (GAAD).

Would you be able to update this translation before then? Or, should we ask someone else to update it?

The updates needed are listed in the changelog at:
	https://www.w3.org/WAI/standards-guidelines/changelog/
	
Here is the file:
https://raw.githubusercontent.com/w3c/wai-std-gl-overview/master/content/index.zh-hans.md

You can submit the edits as a pull request, or sent the updated file to group-wai-translations@w3.org

**Comment by ruoxiran** [comment]
Hi Shawn, Changlog has been updated in PR #60 , please help review it.
